CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS sessions (
    token_hash TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS sessions_expiry ON sessions(expires_at);
CREATE TABLE IF NOT EXISTS surveys (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    answers_json JSONB NOT NULL,
    state_json JSONB,
    revision INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS programs (
    id TEXT NOT NULL,
    admission_year INTEGER NOT NULL,
    active INTEGER NOT NULL,
    is_demo INTEGER NOT NULL,
    data_json JSONB NOT NULL,
    PRIMARY KEY(id, admission_year)
);
CREATE INDEX IF NOT EXISTS programs_cycle ON programs(admission_year,active,is_demo);
